### PR TITLE
Add RPM specification file

### PR DESCRIPTION
**Pull request by mmerklinger**
This PR adds a RPM specification file to build the package on Fedora.

- Adds RPM specification file `python3-nitrokey.spec` and patch `protobuf.patch`.
- Adds a CI pipeline job to make sure the package versions in `pyproject.toml` and `python3-nitrokey.spec` are the same.

The new CI job needs to run on a Fedora container, because the RPM tools ob Debian don't understand the contained RPM macros. For new releases the version number must be raised in `pyproject.toml` and `python3-nitrokey.spec`.

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
How will the rpm file be used?  Will we add a CI job to this repository that builds the package?

**Comment by mmerklinger** [comment]
No, the package is build on Fedora COPR. In COPR we add a project, which is a RPM repository. In this RPM repository we reference the RPM specification file in this Git repository. From COPR we can request new builds of the package.

**Comment by robin-nitrokey** [comment]
Does this mean we also need to update the changelog in the spec file if we release a new version?

**Comment by mmerklinger** [comment]
No, the changelog in the spec file is for changes to the spec file itself, not the packaged software. You don't need to do anything there.

**Comment by robin-nitrokey** [comment]
I see.  Anyway, can you please add an `update-version` target to the Makefile that bumps the version to the output of `poetry version --short`?  Something like this should work:

```
sed "/^Version/s/ [[:digit:]].*/ ${VERSION}/" python3-nitrokey.spec
```

**Review by robin-nitrokey — APPROVED** [review]

**Pull request merged**
